name: sqllitecrud
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  sqflite: ^2.2.8+4
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  flutter_expandable_fab: ^1.8.1
  scrollable_positioned_list: ^0.3.5
  gradient_slide_to_act: ^0.0.2
  swipeable_tile: ^2.0.0+3
  vibration: ^1.8.1
  intl: ^0.18.1
  rename: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/LogoNew.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/background/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets\fonts\ubuntu\Ubuntu-Bold.ttf
          weight: 700
        - asset: assets\fonts\ubuntu\Ubuntu-Italic.ttf
          style: italic
        - asset: assets\fonts\ubuntu\Ubuntu-Regular.ttf
